/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as NotificationsIdRouteImport } from './routes/notifications.$id'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AboutWhoWeAreRouteImport } from './routes/about.who-we-are'
import { Route as AboutOurRoleRouteImport } from './routes/about.our-role'
import { Route as AboutMissionVisionRouteImport } from './routes/about.mission-vision'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const NotificationsIdRoute = NotificationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotificationsRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AboutWhoWeAreRoute = AboutWhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => AboutRoute,
} as any)
const AboutOurRoleRoute = AboutOurRoleRouteImport.update({
  id: '/our-role',
  path: '/our-role',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMissionVisionRoute = AboutMissionVisionRouteImport.update({
  id: '/mission-vision',
  path: '/mission-vision',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/products': typeof ProductsRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/mission-vision': typeof AboutMissionVisionRoute
  '/about/our-role': typeof AboutOurRoleRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/mission-vision': typeof AboutMissionVisionRoute
  '/about/our-role': typeof AboutOurRoleRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/products': typeof ProductsRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/mission-vision': typeof AboutMissionVisionRoute
  '/about/our-role': typeof AboutOurRoleRoute
  '/about/who-we-are': typeof AboutWhoWeAreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/notifications/$id': typeof NotificationsIdRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/notifications'
    | '/products'
    | '/programs'
    | '/sitemap.xml'
    | '/about/mission-vision'
    | '/about/our-role'
    | '/about/who-we-are'
    | '/admin/login'
    | '/admin/notices'
    | '/notifications/$id'
    | '/programs/$slug'
    | '/about/'
    | '/admin/'
    | '/notifications/'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/sitemap.xml'
    | '/about/mission-vision'
    | '/about/our-role'
    | '/about/who-we-are'
    | '/admin/login'
    | '/admin/notices'
    | '/notifications/$id'
    | '/programs/$slug'
    | '/about'
    | '/admin'
    | '/notifications'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/notifications'
    | '/products'
    | '/programs'
    | '/sitemap.xml'
    | '/about/mission-vision'
    | '/about/our-role'
    | '/about/who-we-are'
    | '/admin/login'
    | '/admin/notices'
    | '/notifications/$id'
    | '/programs/$slug'
    | '/about/'
    | '/admin/'
    | '/notifications/'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  NotificationsRoute: typeof NotificationsRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/notifications/$id': {
      id: '/notifications/$id'
      path: '/$id'
      fullPath: '/notifications/$id'
      preLoaderRoute: typeof NotificationsIdRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/who-we-are': {
      id: '/about/who-we-are'
      path: '/who-we-are'
      fullPath: '/about/who-we-are'
      preLoaderRoute: typeof AboutWhoWeAreRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/our-role': {
      id: '/about/our-role'
      path: '/our-role'
      fullPath: '/about/our-role'
      preLoaderRoute: typeof AboutOurRoleRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/mission-vision': {
      id: '/about/mission-vision'
      path: '/mission-vision'
      fullPath: '/about/mission-vision'
      preLoaderRoute: typeof AboutMissionVisionRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutMissionVisionRoute: typeof AboutMissionVisionRoute
  AboutOurRoleRoute: typeof AboutOurRoleRoute
  AboutWhoWeAreRoute: typeof AboutWhoWeAreRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutMissionVisionRoute: AboutMissionVisionRoute,
  AboutOurRoleRoute: AboutOurRoleRoute,
  AboutWhoWeAreRoute: AboutWhoWeAreRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NotificationsRouteChildren {
  NotificationsIdRoute: typeof NotificationsIdRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsIdRoute: NotificationsIdRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  NotificationsRoute: NotificationsRouteWithChildren,
  ProductsRoute: ProductsRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
